name: Run Tests on PR to Test Branch

on:
  pull_request:
    branches:
      - test
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetches the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adjust to match your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a `requirements.txt` file

      - name: Run tests with pytest
        run: pytest --maxfail=5 --disable-warnings --cov=.

      - name: Upload test results (if needed)
        if: failure()
        uses: actions/upload-artifact@v4  
        with:
          name: test-results
          path: .pytest_cache